### ISSUE TITLE
Hi Sir, can you guide how to make import csv in sqlite

### ISSUE THREAD

**Issue by HakimRahim46** [javico2609/flutter-challenges#14]
I really don't understand how to start with because i don't know how the sqlite structure that you build so that i can't call the because it has so many file....Can you guide me how to do it? Your help will be really helpful for me.

**Comment by javico2609** [comment]
Hi.

1. Create and design your database based on the data you want to save ( follow the sql best practice guide ), sqlite it's similar to this tech.
2. Generate your DB and init your table structure. 
[call init database when your app start](https://github.com/javico2609/flutter-challenges/blob/837d694fccc93df6cc58127500015029e84b9581/lib/environment.dart#L25)
[init database](https://github.com/javico2609/flutter-challenges/blob/837d694fccc93df6cc58127500015029e84b9581/lib/services/database.service.dart#L10)

3. If you have a lot of data to save in your local database my advice it's used another solution because remember phones have limit resource.
